# Generated by Django 4.2.8 on 2024-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('computer_name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('application', models.CharField(max_length=255)),
                ('window_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
            ],
        ),
    ]
